const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const savedTheme=localStorage.getItem('ltd-explainer-theme');
const initialTheme=savedTheme==='light'?'light':'dark';
document.documentElement.dataset.theme=initialTheme;
function syncThemeButton(){const dark=document.documentElement.dataset.theme==='dark';const button=$('#themeToggle');if(!button)return;button.textContent=dark?'☀':'☾';button.title=dark?'Switch to light mode':'Switch to dark mode';button.setAttribute('aria-label',button.title)}
syncThemeButton();
$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('ltd-explainer-theme',next);syncThemeButton()};
const views=['overview','architecture','technical','educator','student','explainer'];
$$('[data-view]').forEach(btn=>btn.onclick=()=>showView(btn.dataset.view));
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('.slide-count').textContent=`${String(views.indexOf(id)+1).padStart(2,'0')} / 06`;if(id==='explainer')startDemo();}
$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const techDetails={
 react:{icon:'R',name:'React + TypeScript',body:'Builds the fast, responsive workspace teachers and students use in the browser. It keeps complex learning interactions clear and immediate.',example:'In LTD: course authoring, the reading workspace, progress views, chat and interactive exercises.'},
 fastapi:{icon:'F',name:'FastAPI + Python',body:'Coordinates the platform behind the scenes—identity, courses, learning sessions, AI requests, progress and permissions.',example:'In LTD: one secure application layer connects every learner action to the right course and educator.'},
 postgres:{icon:'P',name:'PostgreSQL',body:'Acts as LTD’s learning memory. It preserves the relationships between people, courses, messages, submissions and progress.',example:'In LTD: an educator can return later and see who engaged, what they submitted and where support is needed.'},
 ai:{icon:'✦',name:'OpenAI · Anthropic · Gemini',body:'A provider-flexible intelligence layer supports tutoring, curriculum generation, feedback and evaluation without locking LTD to one model.',example:'In LTD: the tutor responds in lesson context and asks the learner to reason—not simply handing over an answer.'},
 cloudinary:{icon:'C',name:'Cloudinary',body:'Receives and delivers educator-uploaded learning images reliably, so rich course media stays fast and manageable.',example:'In LTD: when a teacher adds an image item, the file uploads to Cloudinary and its delivery URL is saved with the module.'},
 compute:{icon:'›_',name:'Pyodide + Jupyter',body:'Lets students run real Python work. Lightweight code runs instantly in the browser; advanced packages can move to a managed notebook kernel.',example:'In LTD: learners experiment with code and data inside the lesson instead of leaving for another tool.'},
 collab:{icon:'∞',name:'Yjs + WebSockets',body:'Synchronizes shared code and presence in real time, creating a live bridge between learner work and educator guidance.',example:'In LTD: an educator can observe or support a student’s evolving work without waiting for a final submission.'}
};
const tooltip=$('#techTooltip');
$$('.tech-card').forEach(card=>{const show=()=>{const d=techDetails[card.dataset.tech];$('.tooltip-top span',tooltip).textContent=d.icon;$('h3',tooltip).textContent=d.name;$('p',tooltip).textContent=d.body;$('.tooltip-example',tooltip).textContent=d.example;const r=card.getBoundingClientRect();let left=Math.min(innerWidth-350,Math.max(14,r.left+r.width/2-165));let top=r.top-220;if(top<75)top=r.bottom+12;tooltip.style.left=left+'px';tooltip.style.top=top+'px';tooltip.classList.add('show')};card.addEventListener('mouseenter',show);card.addEventListener('focus',show);card.addEventListener('mouseleave',()=>tooltip.classList.remove('show'));card.addEventListener('blur',()=>tooltip.classList.remove('show'))});

const teacherSteps=[
 {title:'Choose a course',desc:'The Course Manager keeps every program and module in one place.',screen:'courses',cursor:[42,55]},
 {title:'Create a module',desc:'Start a reading or coding module and set the learning intent.',screen:'author',cursor:[37,34]},
 {title:'Compose the experience',desc:'Mix text, video, interactive HTML, executable code, notebooks, and reflection.',screen:'authorItems',cursor:[46,68]},
 {title:'Preview & publish',desc:'See the student experience before publishing it to the academy.',screen:'preview',cursor:[80,68]},
 {title:'Observe progress',desc:'Engagement, submitted work, chats, and reflections reveal where support is needed.',screen:'progress',cursor:[63,48]}
];
const studentSteps=[
 {title:'Enter the learning journey',desc:'Students see a clear sequence of sections and what comes next.',screen:'studentRead',cursor:[24,35]},
 {title:'Look attentively',desc:'Focused content and comprehension checks turn reading into active engagement.',screen:'studentInteractive',cursor:[53,60]},
 {title:'Have a guided conversation',desc:'Watch a student ask LTD for help. The tutor uses lesson context and prompts the learner to reason.',screen:'studentConversation',cursor:[40,67]},
 {title:'Learn by doing',desc:'Executable code and notebooks let students test ideas, not just read about them.',screen:'studentCode',cursor:[54,64]},
 {title:'Reflect & progress',desc:'A submitted reflection closes the loop and makes understanding visible.',screen:'studentReflect',cursor:[54,68]}
];
let role='teacher',index=0,playing=true,timer=null,speed=1,started=false;
function steps(){return role==='teacher'?teacherSteps:studentSteps}
function startDemo(){if(!started){started=true;renderStep();schedule()}}
function schedule(){clearTimeout(timer);const hold=steps()[index]?.screen==='studentConversation'?6500:4300;if(playing)timer=setTimeout(()=>{index=(index+1)%steps().length;renderStep();schedule()},hold/speed)}
function renderStep(){const data=steps()[index];renderList();$('#annotation span').textContent=String(index+1).padStart(2,'0');$('#annotation b').textContent=data.title;$('#annotation p').textContent=data.desc;$('#demoStage').innerHTML=screen(data.screen);$('#demoProgress').style.width=`${((index+1)/steps().length)*100}%`;const c=$('#cursor');c.style.left=data.cursor[0]+'%';c.style.top=data.cursor[1]+'%';setTimeout(()=>{$('.target')?.classList.add('spotlight');bindSimulation();if(data.screen==='studentConversation')runConversation()},500)}
function renderList(){$('#stepList').innerHTML=steps().map((s,i)=>`<button data-step="${i}" class="${i===index?'active':''} ${i<index?'done':''}"><span>${i<index?'✓':i+1}</span>${s.title}</button>`).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{index=+b.dataset.step;playing=false;syncPlay();renderStep();schedule()})}
function syncPlay(){$('#playPause').innerHTML=playing?'Ⅱ <span>Pause</span>':'▶ <span>Play</span>'}
$$('[data-role]').forEach(btn=>btn.onclick=()=>{role=btn.dataset.role;index=0;$$('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===role));renderStep();schedule()});
$('#playPause').onclick=()=>{playing=!playing;syncPlay();schedule()};$('#next').onclick=()=>{index=(index+1)%steps().length;renderStep();schedule()};$('#prev').onclick=()=>{index=(index-1+steps().length)%steps().length;renderStep();schedule()};$('#restart').onclick=()=>{index=0;playing=true;syncPlay();renderStep();schedule()};$('#speed').onchange=e=>{speed=+e.target.value;schedule()};
function nav(title,sub='Educator workspace'){return `<div class="app-nav"><b>${title}</b><span>${sub}</span><div class="avatar">TT</div></div>`}
function courses(){return `<div class="app-screen">${nav('Course Manager')}<div class="screen-body"><h2 class="screen-title">Course Manager</h2><p class="screen-sub">Create, organize, and manage active learning experiences.</p><div class="course-grid"><div class="course-card target highlight"><span class="tag">ACTIVE COURSE</span><h4>AI & Creative Problem Solving</h4><p>4 modules · 28 learners</p><button class="primary-btn">Open course →</button></div><div class="course-card"><span class="tag">DRAFT</span><h4>Introduction to Python</h4><p>3 modules · Draft</p></div><div class="course-card"><span class="tag">ACTIVE COURSE</span><h4>Design Thinking Studio</h4><p>5 modules · 19 learners</p></div></div></div></div>`}
function author(items=false,preview=false){return `<div class="app-screen">${nav('AI & Creative Problem Solving','Course Manager / Module editor')}<div class="author-layout"><aside class="author-toc"><b>Module structure</b><div class="toc-item active">1. How AI learns</div><div class="toc-item">2. Patterns & data</div><div class="toc-item">3. Build a classifier</div><div class="toc-item">＋ Add section</div></aside><div class="author-canvas"><span class="field-label">MODULE TITLE</span><div class="fake-input ${!items&&!preview?'target':''}">How AI learns from examples</div><span class="field-label">LEARNING GOAL</span><div class="fake-input">Learners can explain how examples influence a model's output.</div><span class="field-label">SECTION ITEMS</span><div class="item-row ${items?'target':''}"><button class="item-chip">▤ Text</button><button class="item-chip active">⌘ Interactive HTML</button><button class="item-chip">&lt;/&gt; Code</button><button class="item-chip">▱ Notebook</button><button class="item-chip">◉ Reflection</button></div><div class="content-card"><h4>Interactive: Train a tiny classifier</h4><p>Students adjust examples and observe how the model changes its prediction.</p></div><button class="primary-btn" style="margin-top:12px">Save module</button></div><aside class="preview-panel"><h4>Student preview</h4><div class="phone-preview ${preview?'target':''}"><b>How AI learns</b><p>Models learn patterns from examples. Change the examples below and observe the result.</p><div class="interactive-sim"><div class="sim-question">Which set creates the clearest pattern?</div><div class="sim-options"><button>A</button><button class="selected">B ✓</button></div></div></div></aside></div></div>`}
function progress(){return `<div class="app-screen">${nav('Student Progress')}<div class="screen-body"><h2 class="screen-title">Student Progress</h2><p class="screen-sub">AI & Creative Problem Solving · 28 learners</p><div class="content-card target" style="margin-top:20px"><table style="width:100%;border-collapse:collapse;font-size:10px"><tr style="color:#839297;text-align:left"><th style="padding:10px">LEARNER</th><th>MODULES</th><th>ENGAGEMENT</th><th>REFLECTION</th><th>NEEDS ATTENTION</th></tr><tr><td style="padding:12px 10px;border-top:1px solid #e3eaeb"><b>Amara O.</b></td><td>4 / 4</td><td>High</td><td>Strong</td><td style="color:#2a9d72">On track</td></tr><tr><td style="padding:12px 10px;border-top:1px solid #e3eaeb"><b>Daniel K.</b></td><td>2 / 4</td><td>Medium</td><td>Developing</td><td style="color:#d27b43">Review code</td></tr><tr><td style="padding:12px 10px;border-top:1px solid #e3eaeb"><b>Zara A.</b></td><td>3 / 4</td><td>High</td><td>Strong</td><td style="color:#2a9d72">On track</td></tr></table></div></div></div>`}
function student(type){let main=`<div class="content-card"><h4>Why examples matter</h4><p>An AI model looks for patterns across the examples it receives. The quality and variety of those examples shape what the model can recognize.</p></div>`;let chat=`<div class="bubble ai">Welcome back. As you work, I can help you reason through the lesson.</div><div class="quick-prompts"><span>Explain simply</span><span>Give an example</span><span>Test my knowledge</span></div>`;if(type==='interactive')main+=`<div class="content-card target"><h4>Interactive Content</h4><div class="html-lab"><b style="font-size:9px">Change the diversity of the training examples</b><div class="html-viz"><i></i><i></i><i></i><i></i></div><input class="html-slider" type="range" min="1" max="4" value="3"></div></div>`;if(type==='conversation')chat=`<div class="bubble ai">Let’s explore together. What do you notice about the examples in the chart?</div><div id="studentTyped" class="bubble me typed-caret target"></div><div id="aiThinking" class="bubble ai thinking" hidden><i></i><i></i><i></i></div><div id="aiTyped" class="bubble ai typed-caret" hidden></div>`;if(type==='code')main+=`<div class="content-card target"><h4>Code</h4><p>Change the training example, then run the cell.</p><div class="code-box"><span style="color:#77c5d4">examples</span> = ["red circle", "red square"]<br>model.fit(examples)<br><span style="color:#dff66c">print</span>(model.predict("blue circle"))</div><button class="primary-btn" style="margin-top:8px">▶ Run code</button></div>`;if(type==='reflect')main+=`<div class="content-card target"><h4>Reflection</h4><p>In your own words, explain why varied examples help a model.</p><div class="reflection" contenteditable="true">Varied examples help the model focus on the pattern that matters, instead of memorizing one color or shape...</div><button class="primary-btn" data-submit style="margin-top:8px">Submit reflection</button></div>`;return `<div class="app-screen">${nav('How AI learns','Student learning session')}<div class="module-topbar"><span>☰</span><b>How AI learns from examples</b><div class="section-controls"><span>‹ Previous</span><span>Section 1 of 3</span><span>Next ›</span></div></div><div class="student-screen"><aside class="student-toc"><b style="font-size:11px">Table of Contents</b><div class="toc-item active target">✓ How AI learns</div><div class="toc-item">○ Patterns & data</div><div class="toc-item">🔒 Build a classifier</div></aside><aside class="student-chat"><header><span>✦ Ask LTD</span><small>Learning companion</small></header><div class="chat-body">${chat}</div><div class="ltd-chat-input"><span>What do you think about the reading material?</span><b>➤</b></div></aside><main class="student-content"><span class="tag">SECTION 1 OF 3</span><h2 class="screen-title" style="font-size:20px;margin-top:5px">How AI learns from examples</h2>${main}</main></div></div>`}
function screen(name){if(name==='courses')return courses();if(name==='author')return author();if(name==='authorItems')return author(true);if(name==='preview')return author(false,true);if(name==='progress')return progress();return student(name.replace('student','').toLowerCase()||'read')}
function bindSimulation(){$$('[data-option]').forEach(b=>b.onclick=()=>{$$('[data-option]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('.html-slider')?.addEventListener('input',e=>{$$('.html-viz i').forEach((bar,i)=>{bar.style.height=(20+(i+1)*11+Number(e.target.value)*i*5)+'%';bar.style.opacity=i<Number(e.target.value)?'1':'.28'})});$('[data-submit]')?.addEventListener('click',()=>{$('#demoStage').insertAdjacentHTML('beforeend','<div class="toast">✓ Reflection submitted. Progress saved.</div>')})}
function typeInto(el,text,delay=27){return new Promise(resolve=>{let i=0;const tick=()=>{if(!document.contains(el))return resolve();el.textContent=text.slice(0,i++);if(i<=text.length)setTimeout(tick,delay);else{el.classList.remove('typed-caret');resolve()}};tick()})}
async function runConversation(){const user=$('#studentTyped'),thinking=$('#aiThinking'),ai=$('#aiTyped');if(!user)return;await new Promise(r=>setTimeout(r,500));await typeInto(user,'The model only saw red shapes, so it may think colour is the important pattern.',18);if(!document.contains(user))return;thinking.hidden=false;await new Promise(r=>setTimeout(r,850));if(!document.contains(thinking))return;thinking.hidden=true;ai.hidden=false;await typeInto(ai,'That is a strong observation. What new example would you add to test whether the model learned colour or shape?',15)}
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#prev').click();if(e.key===' '&&$('.view.active').id==='explainer'){e.preventDefault();$('#playPause').click()}});
