(()=>{
window.LTD_CEO_FLOW_V3=true;
const q=(s,p=document)=>p.querySelector(s),qa=(s,p=document)=>[...p.querySelectorAll(s)];
q('#overview .slide').innerHTML=`<div class="slide-kicker">SEQHUB AI ACADEMY · POWERED BY LTD</div><h1>Real mentors help students build <em>real AI projects.</em></h1><p class="lead">LTD prepares the learning between live sessions—so mentor time begins with evidence, questions, and work worth advancing.</p><div class="academy-story"><div class="academy-person"><div class="persona-icon">◎</div><span class="eyebrow">EDUCATOR / MENTOR</span><h3>Shapes the learning journey</h3><p>Sets goals, curates experiences, reviews evidence, and challenges the learner live.</p><small>HUMAN EXPERTISE</small></div><div class="academy-bridge"><b>→</b>designs purposeful preparation</div><div class="academy-ltd"><span>LTD LEARNING PLATFORM</span><h3>Explore · Practice · Reflect</h3><p>Rich modules, contextual AI guidance, code, notebooks, reflection, and visible learning evidence.</p><div class="ltd-cycle"><i>LOOK</i><i>THINK</i><i>DO</i></div></div><div class="academy-bridge"><b>→</b>arrives ready to go deeper</div><div class="academy-person"><div class="persona-icon">✦</div><span class="eyebrow">STUDENT</span><h3>Builds, questions, and creates</h3><p>Prepares independently, collaborates with a mentor, and advances meaningful project work.</p><small>LEARNER AGENCY</small></div></div><div class="human-outcome"><span>THE ACADEMY CONNECTS PEOPLE</span><b>LTD enriches asynchronous preparation</b><b>→ Live mentor session → Real project artifact</b></div>`;
q('#architecture .slide').innerHTML=`<div class="slide-head"><div><div class="slide-kicker">LTD SYSTEM OVERVIEW · CAPABILITY FIRST</div><h2>What the platform enables—and what powers it.</h2></div><p>Hover over any capability to see how it works in LTD.</p></div><div class="cap-grid"><div class="cap-card" data-detail="Educators author courses and monitor evidence; students read, chat, interact, code, and reflect in one responsive workspace."><span>01 · LEARNING EXPERIENCE</span><h3>Create and participate</h3><p>Mentor authoring, student learning, progress views, chat, and interactive activities.</p><b class="cap-tech">React + TypeScript</b></div><div class="cap-card" data-detail="Coordinates courses, sessions, permissions, progress, integrations, and each request to the appropriate service."><span>02 · PLATFORM COORDINATION</span><h3>Keep every action connected</h3><p>One application layer coordinates the journey from educator intent to learner evidence.</p><b class="cap-tech">FastAPI + Python</b></div><div class="cap-card" data-detail="Preserves people, curriculum, conversations, submissions, progress, and evidence so learning continues across sessions."><span>03 · LEARNING MEMORY</span><h3>Remember the journey</h3><p>Course context, learner history, chats, work, reflection, and progress remain connected.</p><b class="cap-tech">PostgreSQL</b></div><div class="cap-card" data-detail="Combines educator intent, learner context, conversation history and activity-specific tutoring rules before selecting an AI provider."><span>04 · ADAPTIVE GUIDANCE</span><h3>Guide without replacing thinking</h3><p>The LTD Learning Orchestrator asks, hints, checks evidence, and supports reflection.</p><b class="cap-tech">OpenAI · Anthropic · Gemini</b></div><div class="cap-card" data-detail="Educator-uploaded images are transformed, optimized, and delivered quickly across devices without burdening the learning application."><span>05 · RICH LEARNING MEDIA</span><h3>Deliver visual experiences quickly</h3><p>Optimized images and media make modules visual, responsive, and dependable.</p><b class="cap-tech">Cloudinary</b></div><div class="cap-card" data-detail="Lightweight Python runs instantly in the browser; advanced notebook work can use Jupyter or move between LTD, Drive, and Colab."><span>06 · PRACTICE & COMPUTATION</span><h3>Turn concepts into real work</h3><p>Interactive HTML, browser Python, notebooks, Drive sync, and Colab support deeper practice.</p><b class="cap-tech">Pyodide · Jupyter · Drive · Colab</b></div></div><div class="arch-note"><b>Capability → learner experience → enabling technology.</b><span>The stack is valuable because of the learning it makes possible.</span></div>`;
q('#technical .slide').className='slide ceo-flow-slide';
q('#technical .slide').innerHTML=`<div class="ceo-flow-head"><div><div class="slide-kicker">CEO VIEW · LIVE LEARNING DATA FLOW</div><h2>When a student asks LTD AI a question.</h2></div><div class="ceo-controls"><button id="ceoRestart">↺ Restart</button><button id="ceoPrev">‹</button><button id="ceoPlay" class="primary">Ⅱ Pause</button><button id="ceoNext">›</button><select id="ceoSpeed"><option value="1">1×</option><option value="1.5">1.5×</option><option value=".6">0.6×</option></select><button id="devToggle">Developer details</button></div></div><div class="ceo-flow-body"><div class="ceo-map"><div class="ceo-node n-student" data-ceo-node="student"><span>1</span><b>Student question</b><small>Asked inside the current React learning module</small></div><div class="ceo-node n-context" data-ceo-node="context"><span>2</span><b>Learning context</b><small>Educator goal · current item · success criteria</small></div><div class="ceo-node n-memory" data-ceo-node="memory"><span>3</span><b>Learning memory</b><small>Conversation history · progress · prior evidence</small></div><div class="ceo-node n-orchestrator" data-ceo-node="orchestrator"><span>4</span><b>LTD Learning Orchestrator</b><small>Combines intent, context, history, and tutoring rules</small></div><div class="ceo-node n-provider" data-ceo-node="provider"><span>5</span><b>Selected AI provider</b><small>Generates guidance from a grounded request</small></div><div class="ceo-node n-response" data-ceo-node="response"><span>6</span><b>Guidance + evidence</b><small>Streams back to the learner and saves the exchange</small></div><svg class="ceo-lines" viewBox="0 0 1000 500" preserveAspectRatio="none"><path data-ceo-path="question" d="M210 250 C250 250 250 115 280 115"/><path data-ceo-path="memory" d="M370 180 L370 320"/><path data-ceo-path="assemble" d="M460 115 C520 115 480 250 520 250"/><path data-ceo-path="history" d="M460 385 C520 385 480 280 520 280"/><path data-ceo-path="provider" d="M730 245 C790 230 760 120 790 120"/><path data-ceo-path="return" d="M880 180 L880 320"/><path data-ceo-path="guide" d="M790 385 C650 470 350 470 205 295"/></svg></div><aside class="ceo-story"><div class="ceo-story-top"><span id="ceoStepNo">01</span><div><small>NOW HAPPENING</small><h3 id="ceoStepTitle"></h3></div></div><p id="ceoStepDesc"></p><div class="ceo-payload" id="ceoPayload"></div><div class="ceo-timeline" id="ceoTimeline"></div></aside></div><div class="ceo-flow-result"><span>OUTCOME</span><b>The student receives guidance grounded in the educator’s intent—not a generic answer—and the exchange becomes evidence for the next human mentor session.</b></div><div class="dev-details" id="devDetails"><b>Developer deployment detail</b><br>React is served through nginx on AWS EC2; Uvicorn runs FastAPI workers. This infrastructure supports the experience but is intentionally removed from the CEO story.</div>`;
q('#educator .journey-line').innerHTML=`<div class="journey-step active"><span>01</span><div class="step-icon">＋</div><h3>Set educator intent</h3><p>Define goals, success criteria, and the project outcome.</p><small>LEARNING DESIGN</small></div><div class="journey-arrow">→</div><div class="journey-step"><span>02</span><div class="step-icon">▤</div><h3>Compose rich modules</h3><p>Choose the right format for each learning action.</p><div class="item-mini"><i>Text</i><i>Image</i><i>Video</i><i>HTML</i><i>Code</i><i>Notebook</i><i>Reflection</i></div><small>8 ITEM TYPES</small></div><div class="journey-arrow">→</div><div class="journey-step"><span>03</span><div class="step-icon">✦</div><h3>Shape AI guidance</h3><p>Control context, tutoring rules, reflection, and progression.</p><small>LTD ORCHESTRATOR</small></div><div class="journey-arrow">→</div><div class="journey-step journey-end"><span>04</span><div class="step-icon">↗</div><h3>Prepare live mentorship</h3><p>Use chats, code, checks, and reflection to focus the next session.</p><small>HUMAN MENTOR HANDOFF</small></div>`;
q('#student .slide-head h2').textContent='Prepare independently. Go deeper with a human mentor.';
q('#student .slide-head>p').textContent='LTD supports the work between sessions; mentors help students challenge assumptions and advance real projects.';
q('#student .agency-note').innerHTML=`<span class="shield">✓</span><div><b>From preparation to creation</b><small>Explore → check understanding → discuss with LTD → practice → reflect → meet a mentor → advance a real artifact.</small></div><div class="progress-pill"><i></i> Portfolio-worthy work</div>`;
const steps=[
 {t:'The learner asks in context',d:'The student is already inside a module and asks LTD about the activity in front of them.',p:'Question + current module item',n:['student'],x:['question']},
 {t:'Educator intent is attached',d:'LTD adds the learning goal, success criteria, current content, and the kind of help the educator allows.',p:'Goal · success criteria · item context',n:['context'],x:['question']},
 {t:'Learning memory is retrieved',d:'Relevant conversation history, progress, and prior evidence keep the exchange continuous and personal.',p:'Conversation history · progress · evidence',n:['memory'],x:['memory']},
 {t:'The learning request is orchestrated',d:'The LTD Learning Orchestrator combines educator intent, learner context, history, endpoint-specific prompts, and tutoring rules.',p:'Intent + context + history + tutoring rules',n:['orchestrator'],x:['assemble','history']},
 {t:'The right intelligence is used',d:'The grounded request goes to the configured AI provider without locking LTD to one model.',p:'Provider-flexible grounded request',n:['provider'],x:['provider']},
 {t:'Guidance streams back',d:'The response returns progressively and deliberately guides thinking instead of simply giving away an answer.',p:'“What evidence in your result supports that?”',n:['response'],x:['return']},
 {t:'The exchange becomes learning evidence',d:'The question and response are saved, visible in the learning trail, and can inform the next live mentor session.',p:'Saved conversation → mentor insight',n:['response','student'],x:['guide']}
];
let i=0,playing=true,timer;
function render(){const s=steps[i];qa('[data-ceo-node]').forEach(n=>{const first=steps.findIndex(z=>z.n.includes(n.dataset.ceoNode));n.classList.toggle('active',s.n.includes(n.dataset.ceoNode));n.classList.toggle('done',first>=0&&first<i)});qa('[data-ceo-path]').forEach(p=>p.classList.toggle('active',s.x.includes(p.dataset.ceoPath)));q('#ceoStepNo').textContent=String(i+1).padStart(2,'0');q('#ceoStepTitle').textContent=s.t;q('#ceoStepDesc').textContent=s.d;q('#ceoPayload').textContent=s.p;q('#ceoTimeline').innerHTML=steps.map((z,j)=>`<button data-ceo-step="${j}" class="${i===j?'active':''}">${j<i?'✓':j+1} ${z.t}</button>`).join('');qa('[data-ceo-step]').forEach(b=>b.onclick=()=>{i=+b.dataset.ceoStep;playing=false;sync();render()})}
function sync(){q('#ceoPlay').textContent=playing?'Ⅱ Pause':'▶ Play'}function schedule(){clearTimeout(timer);if(playing&&q('#technical').classList.contains('active'))timer=setTimeout(()=>{i=(i+1)%steps.length;render();schedule()},2600/Number(q('#ceoSpeed').value))}
q('#ceoPlay').onclick=()=>{playing=!playing;sync();schedule()};q('#ceoNext').onclick=()=>{i=(i+1)%steps.length;render();schedule()};q('#ceoPrev').onclick=()=>{i=(i-1+steps.length)%steps.length;render();schedule()};q('#ceoRestart').onclick=()=>{i=0;playing=true;sync();render();schedule()};q('#ceoSpeed').onchange=schedule;q('#devToggle').onclick=()=>q('#devDetails').classList.toggle('show');qa('[data-view="technical"]').forEach(b=>b.addEventListener('click',()=>{render();schedule()}));render();
})();
