// Extended, self-playing LTD product tour. Kept separate from the presentation logic.
(()=>{
window.LTD_TOUR_V2=true;
const q=(s,p=document)=>p.querySelector(s),qa=(s,p=document)=>[...p.querySelectorAll(s)];
const educator=[
 ['ORIENT','Open the Academy workspace','See active courses, cohorts, upcoming mentor sessions and learner signals at a glance.','e-dashboard',[42,38]],
 ['DESIGN','Open a course','Move from the course overview into a structured sequence of project-based modules.','e-course',[45,42]],
 ['DESIGN','Set the learning goal','Define what learners should understand and create before the next live session.','e-goal',[48,45]],
 ['DESIGN','Choose an item type','Build with text, image, video, HTML, code, notebook, reflection, or external resources.','e-library',[52,56]],
 ['CREATE','Add focused reading','Give students concise context and connect it directly to the project question.','e-text',[47,51]],
 ['CREATE','Embed a video','Add a mentor explanation with a clear observation prompt—not passive watching.','e-video',[51,54]],
 ['CREATE','Build interactive HTML','Let learners manipulate a model and immediately see how its behaviour changes.','e-html',[50,57]],
 ['CREATE','Add executable code','Create an in-browser practice cell with starter code, instructions, and expected output.','e-code',[52,60]],
 ['CREATE','Attach a notebook','Use Jupyter or connect a Drive notebook for advanced project work and data analysis.','e-notebook',[53,55]],
 ['GUIDE','Configure LTD AI','Combine the learning goal, success criteria, item context, and tutoring behaviour.','e-ai',[75,48]],
 ['GUIDE','Require productive dialogue','Ask LTD to question, hint, and check reasoning before a learner can progress.','e-dialogue',[75,57]],
 ['ASSESS','Add a reflection','Capture what changed in the learner’s thinking and what they still need from their mentor.','e-reflection',[52,57]],
 ['PUBLISH','Preview as a student','Walk through the exact learner experience before releasing it to the cohort.','e-preview',[72,58]],
 ['OBSERVE','Review learning evidence','See engagement, checks, chat reasoning, code attempts, and reflections—not just completion.','e-progress',[55,48]],
 ['PREPARE','Prepare the live mentor session','Turn asynchronous evidence into a focused agenda for deeper project work with a human mentor.','e-mentor',[58,52]]
];
const learner=[
 ['START','Continue the project journey','Resume exactly where you stopped and see what to complete before meeting your mentor.','s-dashboard',[45,39]],
 ['LOOK','Open the next module','Follow a purposeful sequence from concept to a real AI project deliverable.','s-module',[34,45]],
 ['LOOK','Read with a purpose','Explore concise content connected to the bias-audit project and its research question.','s-text',[52,48]],
 ['LOOK','Watch the mentor explain','Play a short video and look for the specific pattern the educator asks you to notice.','s-video',[52,53]],
 ['THINK','Check your understanding','Choose an answer, receive immediate feedback, and explain the reasoning behind it.','s-check',[52,56]],
 ['THINK','Manipulate interactive HTML','Change the diversity of a dataset and watch the model’s result respond in real time.','s-html',[52,59]],
 ['THINK','Ask LTD AI for help','Start a contextual conversation without leaving the learning module.','s-chat',[75,62]],
 ['THINK','Reason with the AI tutor','LTD asks a follow-up question instead of giving away the answer, keeping the learner in control.','s-chat2',[75,55]],
 ['DO','Run code in the lesson','Edit starter Python, run it instantly, and compare model performance across groups.','s-code',[53,62]],
 ['DO','Continue advanced analysis','Open a connected notebook when the project needs richer packages, data, and charts.','s-notebook',[54,56]],
 ['DO','Use supporting resources','Open a paper, dataset, or project brief while LTD preserves the learning sequence.','s-resource',[50,55]],
 ['REFLECT','Explain what changed','Write a reflection grounded in the experiment and identify the next question to investigate.','s-reflection',[54,59]],
 ['PROGRESS','Submit learning evidence','Save the conversation, code result, and reflection as visible evidence of preparation.','s-progress',[56,52]],
 ['CONNECT','Meet the human mentor','Arrive with a shared evidence brief so live time begins with the learner’s real questions.','s-mentor',[54,50]],
 ['BUILD','Advance a real artifact','Apply mentor feedback to a portfolio-worthy bias audit, application, paper, or presentation.','s-artifact',[55,53]]
];
let tourRole='teacher',tourIndex=0,tourPlaying=true,tourTimer,tourStarted=false,tourSpeed=1,typingRun=0;
const data=()=>tourRole==='teacher'?educator:learner;
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const nav=(title,sub)=>`<div class="tour-nav"><strong>${title}</strong><span class="crumb">${sub}</span><div class="tour-avatar">${tourRole==='teacher'?'TT':'AO'}</div></div>`;
const left=(active=1)=>`<aside class="tour-left"><h5>${tourRole==='teacher'?'MODULE STRUCTURE':'PROJECT JOURNEY'}</h5><button class="done">Project question</button><button class="${active===1?'active':''}">1. Look · Evidence & examples</button><button class="${active===2?'active':''}">2. Think · Test the model</button><button class="${active===3?'active':''}">3. Do · Build the audit</button><button>4. Reflect · Prepare to meet</button></aside>`;
const shell=(title,sub,main,panel='',active=1)=>`<div class="tour-app">${nav(title,sub)}<div class="tour-layout">${left(active)}<main class="tour-canvas">${main}</main><aside class="tour-panel">${panel||'<h5>LEARNING DESIGN</h5><div class="tour-card"><h3>Explore · Practice · Reflect</h3><p>Every item moves the learner toward independent project work and a richer live mentor conversation.</p></div>'}</aside></div></div>`;
const panelAI=(active='context')=>`<h5>LTD AI GUIDANCE</h5><div class="tour-card ${active==='context'?'target':''}"><span class="tour-label">LEARNING CONTEXT</span><p>Goal, success criteria, current item, conversation history, and learner progress.</p></div><div class="tour-card ${active==='rules'?'target':''}"><span class="tour-label">TUTORING RULES</span><p>Ask before telling · request evidence · reveal hints gradually · encourage reflection.</p></div><button class="tour-btn">Save AI guidance</button>`;
function educatorScreen(type){
 if(type==='e-dashboard')return shell('Academy workspace','Educator dashboard',`<h2>Good afternoon, Taiwo</h2><p class="sub">Your courses, learners, and mentor sessions in one place.</p><div class="tour-grid"><div class="tour-card target"><span class="tour-label">ACTIVE COURSE</span><h3>Auditing AI for Bias</h3><p>12 learners · 4 modules · Project Lab</p><button class="tour-btn auto-click">Continue designing →</button></div><div class="tour-card"><span class="tour-label">NEXT LIVE SESSION</span><h3>Thursday · 4:00 PM</h3><p>7 learners have completed their preparation.</p></div></div><div class="tour-grid"><div class="metric"><strong>83%</strong><small>PREPARATION COMPLETE</small></div><div class="metric"><strong>18</strong><small>LEARNING QUESTIONS</small></div></div>`);
 if(type==='e-course')return shell('Auditing AI for Bias','Course overview',`<h2>Build toward a real bias audit</h2><p class="sub">A connected pathway from foundational ideas to an evidence-backed project.</p>${['How models learn patterns','Measure performance across groups','Build the bias audit','Present findings to a mentor'].map((x,i)=>`<div class="tour-card ${i===1?'target':''}"><span class="tour-label">MODULE ${i+1}</span><h3>${x}</h3><p>${i<3?'Explore · Practice · Reflect':'Live mentor milestone · Project artifact'}</p></div>`).join('')}`,`<h5>COURSE OUTCOME</h5><div class="mentor-brief"><b>Meaningful artifact</b><p>Students produce and defend a documented model-bias audit.</p></div>`);
 if(type==='e-library')return shell('Module editor','Add learning item',`<h2>What should learners do next?</h2><p class="sub">Choose the format that best serves the learning goal.</p><div class="item-library target">${[['¶','Text'],['▧','Image'],['▶','Video'],['◇','Interactive HTML'],['</>','Code'],['▤','Notebook'],['↗','External resource'],['◎','Reflection']].map(x=>`<button class="item-tile"><b>${x[0]}</b>${x[1]}</button>`).join('')}</div>`,panelAI(),2);
 if(type==='e-goal')return shell('Module editor','Learning design',`<h2>Measure performance across groups</h2><p class="sub">Set educator intent before choosing technology.</p><span class="tour-label">LEARNING GOAL</span><div class="tour-field target">Learners can identify a misleading aggregate metric and test model performance across demographic groups.</div><span class="tour-label">SUCCESS CRITERIA</span><div class="tour-field">Compare at least two groups · support a claim with evidence · identify one limitation</div><span class="tour-label">LIVE SESSION OUTCOME</span><div class="tour-field">Bring one surprising result and one unresolved question to the mentor.</div>`,panelAI('context'),2);
 if(type==='e-text')return editor('Text item','Why one accuracy score can hide unfairness',`<div class="tour-field target"><b>Overall accuracy can look strong while one group experiences far more errors.</b><br><br>Disaggregate the results. Ask who benefits, who is harmed, and what the metric leaves out.</div>`,'Connect the concept directly to the project question.');
 if(type==='e-video')return editor('Video item','A mentor reads a confusion matrix',`<div class="video-player target"><button class="auto-click">▶</button></div><div class="tour-field"><b>Observation prompt:</b> Which error changes most between Group A and Group B?</div>`,'Cloudinary-backed media stays fast and responsive.');
 if(type==='e-html')return editor('Interactive HTML','Change the dataset, challenge the metric',`<div class="mini-html target auto-grow"><i></i><i></i><i></i><i></i></div><input style="width:100%;accent-color:#0aa0bd" type="range" value="72"><div class="tour-field">Prompt: What changed—and why might the overall score conceal it?</div>`,'A self-contained simulation gives instant visual feedback.');
 if(type==='e-code')return editor('Code item','Calculate group error rates',`<div class="tour-code target"><span style="color:#75ccdc">for</span> group in ["A", "B"]:<br>&nbsp;&nbsp;subset = results[results.group == group]<br>&nbsp;&nbsp;print(group, false_negative_rate(subset))</div><div class="tour-output">Group A: 0.12 &nbsp; · &nbsp; Group B: 0.31</div>`,'Pyodide runs lightweight Python instantly in the browser.');
 if(type==='e-notebook')return editor('Notebook item','Extend the bias audit',`<div class="tour-card target"><span class="tour-label">CONNECTED NOTEBOOK</span><h3>bias-audit-student-copy.ipynb</h3><p>Starter analysis · protected source · individual learner copy</p><span class="tour-pill">Jupyter</span><span class="tour-pill">Google Drive</span><span class="tour-pill">Open in Colab</span></div><button class="tour-btn">Attach notebook</button>`,'Use advanced packages without breaking the LTD journey.');
 if(type==='e-ai'||type==='e-dialogue')return shell('Module editor','AI learning guidance',`<h2>${type==='e-ai'?'Shape the learning companion':'Create productive dialogue'}</h2><p class="sub">The educator controls why, when, and how AI supports this activity.</p><div class="tour-field"><span class="tour-label">ACTIVITY-SPECIFIC CONTEXT</span><br>Use the confusion matrix and the learner’s latest code output.</div><div class="tour-field"><span class="tour-label">EXPECTED LEARNER REASONING</span><br>Names the disparity, cites both rates, and questions the aggregate score.</div><div class="tour-field ${type==='e-dialogue'?'target':''}"><span class="tour-label">PROGRESSION RULE</span><br>Require one learner claim and one piece of evidence before revealing the next hint.</div>`,panelAI(type==='e-ai'?'context':'rules'),3);
 if(type==='e-reflection')return editor('Reflection item','Prepare for your mentor conversation',`<div class="tour-field target">What result surprised you? What evidence supports your interpretation? What would you like to investigate with your mentor?</div><div><span class="tour-pill">Required</span><span class="tour-pill">AI may ask follow-ups</span><span class="tour-pill">Visible in mentor brief</span></div>`,'Reflection turns activity into evidence of thinking.');
 if(type==='e-preview')return shell('Student preview','Measure performance across groups',`<h2>See exactly what Amara will see</h2><p class="sub">Navigate, interact, ask LTD, and verify every progression rule.</p><div class="tour-card target"><span class="tour-label">INTERACTIVE HTML · PREVIEW MODE</span><h3>Challenge the aggregate score</h3><div class="mini-html"><i></i><i></i><i></i><i></i></div></div><button class="tour-btn auto-click">Publish to cohort</button>`,panelAI('rules'),2);
 if(type==='e-progress')return shell('Learning evidence','Cohort progress',`<h2>See preparation—not just completion</h2><p class="sub">Open any learner to review the evidence behind the status.</p><div class="tour-grid"><div class="metric"><strong>10/12</strong><small>READY FOR LIVE SESSION</small></div><div class="metric"><strong>3</strong><small>COMMON MISCONCEPTIONS</small></div></div>${['Amara O. · Ready · Strong evidence','Daniel K. · Review code attempt','Zara A. · Reflection incomplete'].map((x,i)=>`<div class="tour-card ${i===0?'target':''}"><h3>${x}</h3><p>${i===0?'2 checks · 1 code run · 4 chat turns · reflection submitted':'Open learning trail →'}</p></div>`).join('')}`,`<h5>COHORT SIGNALS</h5><div class="tour-card"><b>Most discussed</b><p>Why equal accuracy can still produce unequal harm.</p></div><div class="tour-card"><b>Mentor opportunity</b><p>Compare fairness definitions using student results.</p></div>`);
 return shell('Mentor session brief','Thursday · Project Lab',`<h2>Begin live time where learning gets interesting</h2><p class="sub">LTD turns asynchronous work into a concise, human-readable session brief.</p><div class="mentor-brief target"><span class="tour-label">AMARA'S OPEN QUESTION</span><h3>“Is false-negative parity always the fairest target?”</h3><p>Evidence: compared two groups, found a 19-point gap, and questioned the aggregate metric.</p></div><div class="tour-grid"><div class="tour-card"><b>Explore together</b><p>Test a second fairness definition.</p></div><div class="tour-card"><b>Advance the artifact</b><p>Add findings to the project report.</p></div></div>`,`<h5>HUMAN MENTORSHIP</h5><div class="artifact-card"><h3>Technology prepares the conversation.</h3><p>The mentor challenges assumptions, shares expertise, and helps the student advance real work.</p></div>`);
}
function editor(kind,title,body,note){return shell('Module editor',kind,`<h2>${title}</h2><p class="sub">${kind} · Section 2: Think</p>${body}<div style="margin-top:10px"><button class="tour-btn auto-click">Save item</button> <button class="tour-btn ghost">Preview</button></div>`,`<h5>WHY THIS ITEM</h5><div class="tour-card"><h3>${kind}</h3><p>${note}</p></div>${panelAI()}`,2)}
function chatPanel(stage){return `<h5>ASK LTD · LEARNING COMPANION</h5><div class="chat-stack"><div class="tour-bubble ai">The overall accuracy is 88%. What do the group-level results add to that story?</div>${stage>0?'<div id="tourStudentText" class="tour-bubble me"></div>':''}${stage>1?'<div id="tourAiText" class="tour-bubble ai"></div>':''}</div><div class="chat-compose">Ask about this activity… <b>➤</b></div>`}
function studentScreen(type){
 if(type==='s-dashboard')return shell('My learning','Student workspace',`<h2>Welcome back, Amara</h2><p class="sub">Prepare independently. Bring your strongest questions to your mentor.</p><div class="tour-card target"><span class="tour-label">CONTINUE LEARNING · 62%</span><h3>Auditing AI for Bias</h3><p>Next: Measure performance across groups · 18 min</p><button class="tour-btn auto-click">Continue →</button></div><div class="mentor-brief"><b>Next mentor session · Thursday</b><p>Complete Module 2 and bring one surprising result.</p></div>`,'<h5>YOUR PROJECT</h5><div class="artifact-card"><h3>Model Bias Audit</h3><p>Investigate a real system and produce an evidence-backed report.</p></div>');
 if(type==='s-module')return shell('Auditing AI for Bias','Project journey',`<h2>Measure performance across groups</h2><p class="sub">Explore the idea, test it, then apply it to your own audit.</p>${[['LOOK','Read + mentor video','8 min'],['THINK','Check + interactive experiment','6 min'],['DO','Run the group analysis','12 min'],['REFLECT','Prepare for your mentor','4 min']].map((x,i)=>`<div class="tour-card ${i===0?'target':''}"><span class="tour-label">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}`,chatPanel(0),1);
 if(type==='s-text')return shell('Measure performance across groups','Look · Reading',`<h2>When one score hides two stories</h2><p class="sub">Read with this question: Who might the average fail to represent?</p><div class="tour-card target"><p><b>Overall accuracy can look strong while one group experiences far more errors.</b></p><p>A useful evaluation separates results by the groups affected. The question is not only “How often is the model right?” but also “For whom does it fail, and how?”</p></div><div class="check-option">Mark as understood and continue →</div>`,chatPanel(0),1);
 if(type==='s-video')return shell('Measure performance across groups','Look · Mentor video',`<h2>Read a confusion matrix</h2><p class="sub">As you watch: notice which kind of error changes most.</p><div class="video-player target"><button class="auto-click">Ⅱ</button></div><div class="tour-field"><b>00:42 / 02:18</b> · “Now compare the false negatives—not only total accuracy…”</div>`,chatPanel(0),1);
 if(type==='s-check')return shell('Measure performance across groups','Think · Check',`<h2>What does the aggregate score conceal?</h2><p class="sub">The model is 88% accurate overall, but false-negative rates are 12% and 31%.</p><div class="check-option">A. The model is equally reliable for everyone.</div><div class="check-option selected target">B. One group is more likely to be incorrectly missed. ✓</div><div class="check-option">C. Overall accuracy is too low to interpret.</div><div class="tour-output">Correct. Now explain why the 88% figure alone is incomplete.</div>`,chatPanel(0),2);
 if(type==='s-html')return shell('Measure performance across groups','Think · Interactive HTML',`<h2>Change the data. Challenge the result.</h2><p class="sub">Drag group representation and observe what happens to the metrics.</p><div class="mini-html target auto-grow"><i></i><i></i><i></i><i></i></div><input id="tourRange" style="width:100%;accent-color:#0aa0bd" type="range" min="10" max="90" value="65"><div class="tour-grid"><div class="metric"><strong>88%</strong><small>OVERALL ACCURACY</small></div><div class="metric"><strong>19pt</strong><small>GROUP ERROR GAP</small></div></div>`,chatPanel(0),2);
 if(type==='s-chat'||type==='s-chat2')return shell('Measure performance across groups','Think · Guided conversation',`<h2>Use AI to deepen your reasoning</h2><p class="sub">LTD knows the activity, your result, and the educator’s learning goal.</p><div class="tour-card"><span class="tour-label">YOUR EXPERIMENT</span><h3>88% overall · 12% vs 31% false-negative rate</h3><p>The group gap grew when representation changed.</p></div><div class="tour-card"><b>Progress rule</b><p>Make a claim and cite one result before moving on.</p></div>`,chatPanel(type==='s-chat'?1:2),2);
 if(type==='s-code')return shell('Build the bias audit','Do · Executable code',`<h2>Test the claim with code</h2><p class="sub">Edit the group field, then run the analysis in the lesson.</p><div class="tour-code target"><span style="color:#75ccdc">for</span> group in groups:<br>&nbsp;&nbsp;y = results[results.group == group]<br>&nbsp;&nbsp;print(group, false_negative_rate(y))</div><button id="tourRun" class="tour-btn auto-click" style="margin-top:8px">▶ Run code</button><div id="tourCodeOutput" class="tour-output">Running in browser with Pyodide…</div>`,chatPanel(0),3);
 if(type==='s-notebook')return shell('Build the bias audit','Do · Connected notebook',`<h2>Continue the advanced analysis</h2><p class="sub">Your own notebook copy keeps the project data, charts, and methods together.</p><div class="tour-card target"><span class="tour-label">BIAS-AUDIT-AMARA.IPYNB</span><h3>3 of 6 analysis cells complete</h3><p>Last sync: just now · Google Drive</p><span class="tour-pill">Open in LTD</span><span class="tour-pill">Open in Colab ↗</span></div><div class="tour-output">✓ Notebook progress connected to this learning session.</div>`,chatPanel(0),3);
 if(type==='s-resource')return shell('Build the bias audit','Do · Supporting evidence',`<h2>Compare your finding with research</h2><p class="sub">Use the source to strengthen—or challenge—your interpretation.</p><div class="tour-card target"><span class="tour-label">EXTERNAL RESOURCE · RESEARCH PAPER</span><h3>Fairness and abstraction in sociotechnical systems</h3><p>Guiding prompt: Which assumption in your current metric does this paper challenge?</p><button class="tour-btn">Open resource ↗</button></div>`,chatPanel(0),3);
 if(type==='s-reflection')return shell('Prepare to meet your mentor','Reflect',`<h2>Turn the experiment into a question</h2><p class="sub">Your reflection will appear in the mentor’s session brief.</p><div id="tourReflection" class="tour-field target" style="min-height:90px"></div><button class="tour-btn auto-click">Submit reflection</button>`,chatPanel(0),4);
 if(type==='s-progress')return shell('Module complete','Learning evidence saved',`<h2>You are ready for the live session</h2><p class="sub">LTD saved the trail of work behind your completion.</p><div class="tour-grid"><div class="metric"><strong>2/2</strong><small>CHECKS COMPLETE</small></div><div class="metric"><strong>4</strong><small>AI REASONING TURNS</small></div><div class="metric"><strong>1</strong><small>CODE EXPERIMENT</small></div><div class="metric"><strong>✓</strong><small>REFLECTION READY</small></div></div><div class="tour-output target">Shared with your mentor · Next session Thursday, 4:00 PM</div>`,chatPanel(0),4);
 if(type==='s-mentor')return shell('Live mentor session','Thursday · Project Lab',`<h2>Start with your real question</h2><p class="sub">Your mentor sees what you tried, how you reasoned, and where you are stuck.</p><div class="mentor-brief target"><span class="tour-label">DISCUSS WITH YOUR MENTOR</span><h3>“Is false-negative parity always the fairest target?”</h3><p>Amara found a 19-point gap and wants to compare a second fairness definition.</p></div><div class="tour-card"><b>Today’s live work</b><p>Challenge the metric · rerun the audit · decide what belongs in the report.</p></div>`,'<h5>HUMAN GUIDANCE</h5><div class="tour-card"><h3>Mentor + learner</h3><p>Technology brings the evidence. The human relationship brings judgment, expertise, challenge, and encouragement.</p></div>');
 return shell('Project portfolio','Artifact updated',`<h2>From preparation to meaningful work</h2><p class="sub">Amara applies mentor feedback and advances a project she can explain and defend.</p><div class="artifact-card target"><span class="tour-label">PROJECT ARTIFACT · VERSION 3</span><h3>Bias Audit: Evaluating Unequal Error in a Screening Model</h3><p>Methods · group analysis · fairness trade-offs · limitations · recommendations</p><button class="tour-btn" style="background:#fff;color:#086f88">View project report →</button></div><div class="tour-output">Next milestone: Present findings at Demo Day</div>`,'<h5>ACADEMY OUTCOME</h5><div class="tour-card"><h3>Creator, not consumer</h3><p>A portfolio-ready artifact backed by independent work, critical AI literacy, and mentor-guided depth.</p></div>');
}
const screenFor=name=>name.startsWith('e-')?educatorScreen(name):studentScreen(name);
function renderList(){const list=q('#stepList');if(!list)return;let phase='';list.innerHTML=data().map((s,i)=>{const head=s[0]!==phase?`<div class="tour-phase">${phase=s[0]}</div>`:'';return `${head}<button data-tour-step="${i}" class="${i===tourIndex?'active':''} ${i<tourIndex?'done':''}"><span>${i<tourIndex?'✓':i+1}</span>${s[1]}</button>`}).join('');qa('[data-tour-step]').forEach(b=>b.onclick=()=>{tourIndex=+b.dataset.tourStep;tourPlaying=false;sync();render();});q('[data-tour-step].active')?.scrollIntoView({block:'nearest'});}
function sync(){q('#playPause').innerHTML=tourPlaying?'Ⅱ <span>Pause</span>':'▶ <span>Play</span>';q('#tourRuntime').textContent=`${tourRole==='teacher'?'Educator':'Student'} · ${tourIndex+1}/${data().length} · ~3 min`;}
function render(){const s=data()[tourIndex];typingRun++;renderList();q('#annotation span').textContent=String(tourIndex+1).padStart(2,'0');q('#annotation b').textContent=s[1];q('#annotation p').textContent=s[2];q('#demoStage').innerHTML=screenFor(s[3]);q('#demoProgress').style.width=`${((tourIndex+1)/data().length)*100}%`;const c=q('#cursor');c.style.left=s[4][0]+'%';c.style.top=s[4][1]+'%';setTimeout(()=>q('.target',q('#demoStage'))?.classList.add('spotlight'),350);animate(s[3],typingRun);sync();}
function type(el,text,run,delay=22){let i=0;const tick=()=>{if(run!==typingRun||!document.contains(el))return;el.textContent=text.slice(0,i++);if(i<=text.length)setTimeout(tick,delay)};tick();}
function animate(name,run){setTimeout(()=>{if(run!==typingRun)return;if(name==='s-chat'||name==='s-chat2'){const u=q('#tourStudentText');if(u)type(u,'The overall score hides that Group B is missed much more often—31% compared with 12%.',run,18);if(name==='s-chat2')setTimeout(()=>{const a=q('#tourAiText');if(a)type(a,'Good evidence. What fairness goal would you test next, and what trade-off might it introduce?',run,16)},1900)}if(name==='s-code')setTimeout(()=>{const o=q('#tourCodeOutput');if(o)o.innerHTML='<b>✓ Complete</b> &nbsp; Group A: 0.12 · Group B: 0.31 · Gap: 0.19'},1400);if(name==='s-reflection'){const el=q('#tourReflection');if(el)type(el,'I expected the overall accuracy to tell the full story. My group analysis showed a 19-point false-negative gap. I want to ask my mentor whether equalizing this rate creates another trade-off.',run,12)}},450)}
function schedule(){clearTimeout(tourTimer);if(tourPlaying)tourTimer=setTimeout(()=>{if(tourIndex===data().length-1){if(tourRole==='teacher'){tourRole='student';tourIndex=0;qa('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role==='student'));}else tourIndex=0;}else tourIndex++;render();schedule();},11500/tourSpeed)}
function start(){tourStarted=true;render();schedule()}
qa('[data-view="explainer"]').forEach(b=>b.addEventListener('click',()=>setTimeout(start,0)));
qa('[data-role]').forEach(b=>b.onclick=()=>{tourRole=b.dataset.role;tourIndex=0;tourPlaying=true;qa('[data-role]').forEach(x=>x.classList.toggle('active',x===b));render();schedule()});
q('#playPause').onclick=()=>{tourPlaying=!tourPlaying;sync();schedule()};q('#next').onclick=()=>{tourIndex=(tourIndex+1)%data().length;render();schedule()};q('#prev').onclick=()=>{tourIndex=(tourIndex-1+data().length)%data().length;render();schedule()};q('#restart').onclick=()=>{tourIndex=0;tourPlaying=true;render();schedule()};q('#speed').onchange=e=>{tourSpeed=+e.target.value;schedule()};
if(q('#explainer')?.classList.contains('active'))start();
})();
